### ISSUE TITLE
os.sleep

### ISSUE THREAD

**Issue by Kleadron** [OpenPrograms/skye-Programs#2]
I need an os.sleep so that my simple reactor control program functions properly. Without it, the graphics looks really wierd (as in it looks like a black line on a crt going down the text when a window redraws.)

The os.sleep is needed to create a delay so it doesnt go too fast and so the controls can be registered.

**Comment by skyem123** [comment]
@Kleadron, alright, I have added in some code that should do this, so please test it to make sure it works! I also implemented `os.exit`, so it'd be helpful if you could test that as well, thanks. ^^

**Comment by skyem123** [comment]
Testing has revealed that os.sleep works now, and os.exit is untested but should work, good enough, closing this issue.
